from ..base.api.permissions import AllowAny, PermissionComponent, ResourcePermission, IsAuthenticated


class IsTheSameUser(PermissionComponent):
    def has_permission(self, request, view):
        return request.user.is_authenticated()

    def has_object_permission(self, request, view, obj=None):
        return request.user.is_authenticated() and request.user.pk == obj.pk


class PatientsPermissions(ResourcePermission):
    metadata_perms = IsAuthenticated()
    enough_perms = IsAuthenticated()
    global_perms = None
    retrieve_perms = IsAuthenticated()
    create_perms = AllowAny()
    update_perms = IsAuthenticated()
    partial_update_perms = IsAuthenticated()
    destroy_perms = IsAuthenticated()
    list_perms = IsAuthenticated()
    membership_perms = IsAuthenticated()
    registration_perms = IsAuthenticated()
    group_perms = IsAuthenticated()
    history_perms = IsAuthenticated()
    search_perms = IsAuthenticated()
    medical_certificate_perms = IsAuthenticated()
    medical_certificate_pdf_perms = IsAuthenticated()
    vital_sign_perms = IsAuthenticated()
    vital_sign_pdf_perms = IsAuthenticated()
    clinic_notes_pdf_perms = IsAuthenticated()
    treatment_plan_pdf_perms = IsAuthenticated()
    clinic_notes_perms = IsAuthenticated()
    procedure_perms = IsAuthenticated()
    complete_procedure_perms = IsAuthenticated()
    files_perms = IsAuthenticated()
    copy_prescriptions_perms = IsAuthenticated()
    prescriptions_perms = IsAuthenticated()
    prescriptions_pdf_perms = IsAuthenticated()
    unpaid_prescriptions_perms = IsAuthenticated()
    invoices_perms = IsAuthenticated()
    payment_perms = IsAuthenticated()
    advance_search_perms = IsAuthenticated()
    details_perms = IsAuthenticated()
    patient_appointments_perms = IsAuthenticated()
    inventory_perms = IsAuthenticated()
    combine_clinic_level_patient_report_perms = IsAuthenticated()
    merge_patients_perms = IsAuthenticated()
    patient_notes_perms = IsAuthenticated()
    print_perms = AllowAny()
    combine_patient_report_perms = IsAuthenticated()
    timeline_pdf_perms = IsAuthenticated()
    lab_order_pdf_perms = IsAuthenticated()
    cancel_membership_perms = IsAuthenticated()
    cancel_registration_perms = IsAuthenticated()
    patient_list_perms = IsAuthenticated()
    city_perms = IsAuthenticated()
    state_perms = IsAuthenticated()
    country_perms = IsAuthenticated()
    generate_otp_perms = IsAuthenticated()
    resend_otp_perms = IsAuthenticated()
    verify_otp_perms = IsAuthenticated()
    pending_amount_perms = IsAuthenticated()
    my_agents_perms = IsAuthenticated()
    agents_chain_perms = IsAuthenticated()
    new_patients_perms = IsAuthenticated()
    membership_report_perms = IsAuthenticated()
    first_appointment_perms = IsAuthenticated()
    mlm_report_perms = IsAuthenticated()
    agent_wallet_balance_perms = IsAuthenticated()
    advance_payment_perms = IsAuthenticated()
    active_patients_perms = IsAuthenticated()
    ledger_perms = IsAuthenticated()
    source_perms = IsAuthenticated()
    patient_notes_call_perms = IsAuthenticated()
    app_summary_perms = IsAuthenticated()
    print_ticket_perms = IsAuthenticated()
    cold_calling_perms = IsAuthenticated()
    cron_test_perms = IsAuthenticated()
    allopath_perms = IsAuthenticated()
    team_analysis_perms = IsAuthenticated()
    calling_report_perms = IsAuthenticated()
    bank_details_perms = IsAuthenticated()
    registration_report_perms = IsAuthenticated()
    bbps_bill_perms = AllowAny()
    bbps_payment_perms = AllowAny()
